# Generated by Django 5.0.4 on 2024-06-18 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_autoshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='mid_day',
            field=models.TimeField(default=datetime.time(13, 0)),
            preserve_default=False,
        ),
    ]
