# Generated by Django 5.0.7 on 2024-12-12 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_autoshift_grace_period_at_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoshift',
            name='absent_threshold',
            field=models.DurationField(default=datetime.timedelta(0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoshift',
            name='include_lunch_break_in_full_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autoshift',
            name='include_lunch_break_in_half_day',
            field=models.BooleanField(default=False),
        ),
    ]
