# Generated by Django 5.0.7 on 2024-12-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_autoshift_absent_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoshift',
            name='lunch_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autoshift',
            name='lunch_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autoshift',
            name='lunch_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
