# Generated by Django 5.0.7 on 2024-12-24 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_autoshift_shift_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='absent_threshold',
            field=models.DurationField(default=datetime.timedelta(0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='include_lunch_break_in_full_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shift',
            name='include_lunch_break_in_half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='autoshift',
            name='shift_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
