# Generated by Django 5.0.7 on 2024-12-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_shift_absent_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
