# Generated by Django 5.0.7 on 2025-02-27 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_alter_shift_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCorrectionConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable or disable the auto-correction feature')),
                ('cutoff_time', models.TimeField(default=datetime.time(6, 0), help_text='Time threshold to determine if the current day should be considered or shifted to the previous day')),
            ],
            options={
                'db_table': 'attendance_correction_config',
            },
        ),
    ]
