# Generated by Django 5.0.7 on 2025-01-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_alter_employee_first_weekly_off_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default_pic.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
