# Generated by Django 5.0.7 on 2025-01-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_alter_employee_profile_pic'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['logdate'], name='idx_logdate'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employeeid', 'logdate'], name='idx_employeeid_logdate'),
        ),
        migrations.AddIndex(
            model_name='logs',
            index=models.Index(fields=['employeeid', 'log_datetime'], name='idx_employeeid_logdatetime'),
        ),
    ]
