# Generated by Django 5.0.7 on 2025-01-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_alter_shift_id'),
        ('resource', '0004_attendance_idx_logdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(blank=True, max_length=50, null=True)),
                ('log_datetime', models.DateTimeField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'manual_logs',
            },
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employee_id_f33e0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employee_employe_e43f48_idx',
        ),
        migrations.RenameIndex(
            model_name='logs',
            new_name='logs_emp_logdt',
            old_name='idx_employeeid_logdatetime',
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='idx_employee_id'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id', 'employee_name'], name='idx_employee_id_name'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['bank_account_no', 'bank_name'], name='idx_bank_account_bank_name'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['job_type', 'job_status'], name='idx_job_type_status'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['date_of_joining', 'date_of_leaving'], name='idx_joining_leaving'),
        ),
        migrations.AddIndex(
            model_name='logs',
            index=models.Index(fields=['log_datetime'], name='logs_logdt'),
        ),
        migrations.AddIndex(
            model_name='logs',
            index=models.Index(fields=['direction'], name='logs_dir'),
        ),
        migrations.AddIndex(
            model_name='manuallogs',
            index=models.Index(fields=['employeeid', 'log_datetime'], name='manual_emp_logdt'),
        ),
        migrations.AddIndex(
            model_name='manuallogs',
            index=models.Index(fields=['log_datetime'], name='manual_logdt'),
        ),
        migrations.AddIndex(
            model_name='manuallogs',
            index=models.Index(fields=['direction'], name='manual_dir'),
        ),
    ]
