# Generated by Django 5.0.7 on 2025-01-31 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_manuallogs_remove_employee_employee_id_f33e0d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRoundoffRules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round_off_interval', models.DurationField(default=datetime.timedelta(seconds=900))),
                ('round_off_direction', models.CharField(choices=[('up', 'up'), ('down', 'down'), ('nearest', 'nearest')], default='nearest', max_length=50)),
            ],
            options={
                'db_table': 'overtime_roundoff_rules',
            },
        ),
    ]
