# Generated by Django 5.0.7 on 2025-02-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0007_alter_overtimeroundoffrules_round_off_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField()),
                ('holiday_name', models.CharField(max_length=100)),
                ('holiday_type', models.CharField(choices=[('PH', 'PH'), ('FH', 'FH')], default='PH', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'holiday_list',
                'indexes': [models.Index(fields=['holiday_date'], name='idx_holiday_date'), models.Index(fields=['holiday_name'], name='idx_holiday_name'), models.Index(fields=['holiday_type'], name='idx_holiday_type'), models.Index(fields=['holiday_date', 'holiday_name'], name='idx_holiday_date_name')],
            },
        ),
    ]
