# Generated by Django 5.0.7 on 2025-02-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0008_holidaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaylist',
            name='holiday_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
